AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Table for Laravel Cache

Resources:
  LaravelCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LaravelCache
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: cache_key
          AttributeType: S
      KeySchema:
        - AttributeName: cache_key
          KeyType: HASH
