AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository for Laravel Application

Resources:
  LaravelECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: mnk-user-auth-app

Outputs:
  ECRRepositoryURI:
    Value: !Ref LaravelECR
    Description: URI of the ECR Repository
