AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Cluster with Node Group using provided IAM Roles

Parameters:
  ClusterName:
    Type: String
    Default: my-eks-cluster
    Description: Name of the EKS Cluster.

Resources:
  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      RoleArn: arn:aws:iam::971422685560:role/AmazonEKSAutoClusterRole
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0250022499a3db7f3  # Replace with actual Subnet IDs
          - subnet-014c16cda66c7f078
        SecurityGroupIds:
          - sg-0992135dd56d6615c    # Replace with actual Security Group ID

  NodeGroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      ClusterName: !Ref ClusterName
      NodeRole: arn:aws:iam::971422685560:role/AmazonEKSAutoNodeRole
      ScalingConfig:
        MinSize: 2
        MaxSize: 2
        DesiredSize: 2
      Subnets:
        - subnet-0250022499a3db7f3
        - subnet-014c16cda66c7f078

Outputs:
  EKSClusterName:
    Value: !Ref ClusterName
    Description: The name of the EKS Cluster.
