AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Cluster for Laravel Application

Resources:
  # EKS Cluster Role
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController

  # EKS Node Role
  EKSNodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

  # EKS Cluster
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: LaravelEKSCluster
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0fdc7d89e2b460ee1
          - subnet-0b0a0583d221d317b
        SecurityGroupIds:
          - sg-044b4b6bf5141af7f
      RoleArn: arn:aws:iam::971422685560:role/EKSClusterRole

  # EKS Node Group (Optional, if you want to add nodes directly in the same template)
  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EKSCluster
      NodeRole: arn:aws:iam::971422685560:role/EKSNodeRole
      Subnets:
        - subnet-0fdc7d89e2b460ee1
        - subnet-0b0a0583d221d317b
      InstanceTypes:
        - t3.medium
      ScalingConfig:
        MinSize: 1
        MaxSize: 2
        DesiredSize: 2

Outputs:
  ClusterName:
    Value: !Ref EKSCluster
    Description: Name of the EKS Cluster
