AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL Instance for Laravel Application

Resources:
  # RDS DB Subnet Group
  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for the Laravel RDS instance"
      SubnetIds:
        - subnet-0fdc7d89e2b460ee1
        - subnet-0b0a0583d221d317b # Replace with your actual subnet ID(s)

  # RDS MySQL Instance
  LaravelRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20  # Adjust storage size as needed
      Engine: MySQL
      EngineVersion: 8.0
      MasterUsername: admin # Reference to the username stored in Secrets Manager
      MasterUserPassword: Gajen@97  # Reference to the password stored in Secrets Manager
      DBName: laravel_db
      PubliclyAccessible: false
      MultiAZ: false  # Set to true for high availability
      BackupRetentionPeriod: 7  # Retain backups for 7 days
      VPCSecurityGroups:
        - sg-09c489f9b1744dc49  # Replace with your actual security group ID
      DBSubnetGroupName: !Ref RDSDBSubnetGroup

  # Secrets Manager for the DB password
  DBPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: LaravelRDSPassword
      SecretString: '{"password":"Gajen97_2025"}'  # Valid password (Ensure it meets the AWS RDS password policy)

  # Secrets Manager for the DB username
  DBUsername:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: LaravelDBUsername
      SecretString: '{"username":"admin"}'  # Replace with your actual DB username

Outputs:
  # Output the RDS instance endpoint
  RDSInstanceEndpoint:
    Value: !GetAtt LaravelRDS.Endpoint.Address
    Description: "The RDS endpoint of the Laravel MySQL instance"

  # Output the RDS instance ARN
  RDSInstanceArn:
    Value: !Ref LaravelRDS
    Description: "The ARN of the RDS instance"
