apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: 650251721226.dkr.ecr.us-east-1.amazonaws.com/laravel-app:latest
        ports:
        - containerPort: 8000
