name: CI/CD Pipeline for Laravel with CloudFormation

on:
  push:
    branches:
      - main

jobs:
  provision-infrastructure:
    name: Provision Infrastructure
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Step 3: Deploy CloudFormation Stacks
    - name: Deploy EKS Stack
      run: |
        aws cloudformation deploy \
          --template-file infra/eks.yaml \
          --stack-name LaravelEKS \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Deploy DynamoDB Stack
      run: |
        aws cloudformation deploy \
          --template-file infra/dynamodb.yaml \
          --stack-name LaravelDynamoDB

    - name: Deploy ECR Stack
      run: |
        aws cloudformation deploy \
          --template-file infra/ecr.yaml \
          --stack-name LaravelECR

  build-and-deploy-application:
    name: Build and Deploy Application
    needs: provision-infrastructure
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -f docker/Dockerfile -t laravel-app .
        docker tag laravel-app:latest 650251721226.dkr.ecr.ap-south-1.amazonaws.com/laravel-app:latest

    # Step 3: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 650251721226.dkr.ecr.ap-south-1.amazonaws.com

    # Step 4: Push Docker Image to ECR
    - name: Push Docker Image to ECR
      run: |
        docker push 650251721226.dkr.ecr.ap-south-1.amazonaws.com/laravel-app:latest

    # Step 5: Deploy Docker Image to ECS
    - name: Deploy to ECS
      run: |
        # Update ECS task definition with the new Docker image
        aws ecs register-task-definition \
          --family laravel-app-task \
          --container-definitions "[{
            \"name\": \"laravel-app\",
            \"image\": \"650251721226.dkr.ecr.ap-south-1.amazonaws.com/laravel-app:latest\",
            \"memory\": 512,
            \"cpu\": 256,
            \"essential\": true,
            \"portMappings\": [{\"containerPort\": 80, \"hostPort\": 80}]
          }]"

        # Update ECS service to use the new task definition
        aws ecs update-service \
          --cluster laravel-cluster \
          --service laravel-app-service \
          --force-new-deployment

    # Optional: Output the ECS service URL
    - name: Output ECS Service URL
      run: |
        echo "ECS service URL: http://$(aws ecs describe-services --cluster laravel-cluster --services laravel-app-service --query 'services[0].loadBalancers[0].dnsName' --output text)"

    # Step 6: Deploy to EKS (if applicable)
    - name: Deploy to EKS
      run: |
        kubectl apply -f docker/deployment.yaml
        kubectl apply -f docker/service.yaml
