name: CI/CD Pipeline for Laravel with ECR and EKS

on:
  push:
    branches:
      - main

jobs:
  provision-infrastructure:
    name: Provision Infrastructure
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Region is specified here

    # Step 3: Deploy CloudFormation Stacks (optional steps)
    - name: Deploy EKS Stack
      run: |
        aws cloudformation deploy \
          --template-file infra/eks.yaml \
          --stack-name LaravelEKS \
          --capabilities CAPABILITY_NAMED_IAM
    - name: Deploy DynamoDB Stack
      run: |
        aws cloudformation deploy \
          --template-file infra/dynamodb.yaml \
          --stack-name LaravelDynamoDB
    - name: Deploy ECR Stack
      run: |
        aws cloudformation deploy \
          --template-file infra/ecr.yaml \
          --stack-name LaravelECR

#Depolyment page 
  build-and-deploy:
    name: Build and Deploy DB,ECR to EKS
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Step 3: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Step 4: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=latest
        IMAGE_URI=650251721226.dkr.ecr.ap-south-1.amazonaws.com/laravel-app:$IMAGE_TAG

        echo "Building Docker image with tag: $IMAGE_URI"
        docker build -f docker/Dockerfile -t $IMAGE_URI .

        echo "Pushing Docker image to Amazon ECR"
        docker push $IMAGE_URI

    # Step 5: Update Kubernetes Config for EKS
    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name ${{ secrets.EKS_CLUSTER_NAME }}

    # Step 6: Replace Image URI in Kubernetes Manifest
    - name: Replace Docker Image in Kubernetes Manifest
      run: |
        IMAGE_TAG=latest
        IMAGE_URI=650251721226.dkr.ecr.ap-south-1.amazonaws.com/laravel-app:$IMAGE_TAG

        echo "Replacing DOCKER_IMAGE placeholder with $IMAGE_URI in Kubernetes manifest"
        sed -i.bak "s|DOCKER_IMAGE|$IMAGE_URI|g" docker/deployment.yaml

    # Step 7: Deploy to EKS
    - name: Deploy to EKS
      run: |
        echo "Applying Kubernetes deployment and service manifests"
        kubectl apply -f docker/deployment.yaml
        kubectl apply -f docker/service.yaml
        
    # Step 8: Output EKS Service URL
    - name: Output EKS Service URL
      run: |
        SERVICE_URL=$(kubectl get svc -o=jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}')
        echo "EKS Service URL: http://$SERVICE_URL"
